name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  ANKI_VERSION: 24.11.3

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Normalize image name and tag
        id: prep
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${REPO_LOWER}" >> "$GITHUB_OUTPUT"
          echo "TAG=v${ANKI_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg ANKI_VERSION=${{ env.ANKI_VERSION }} \
            -t ${{ steps.prep.outputs.IMAGE }}:${{ steps.prep.outputs.TAG }} .

      - name: Push Docker image
        run: docker push ${{ steps.prep.outputs.IMAGE }}:${{ steps.prep.outputs.TAG }}
